#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Trigger Helm workflow in Automation repository

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  trigger-workflow:
    name: Trigger Helm workflow
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Trigger Helm workflow using GitHub CLI call
      run: |
        gh workflow run build-helm.yaml --repo https://github.com/galasa-dev/automation
      env:
        GH_TOKEN: ${{ secrets.GALASA_TEAM_GITHUB_TOKEN }}

